# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ioasys' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ioasys
  pod 'Swinject', '~> 2.0.0'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya/RxSwift'
  pod 'Reusable'
  pod 'SwiftLint'
  pod 'R.swift'
  pod 'ReachabilitySwift'
  pod 'RxGesture'
  pod 'RxSwiftUtilities', '~> 2.0.1'
  pod 'lottie-ios'
  pod 'RxSwiftExt'

  target 'ioasysTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ioasysUITests' do
    # Pods for testing
  end

end
